spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtest?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 10
      max-active: 10

  elasticsearch:
    rest:
      enable: true
      uris: localhost:9200
      host: localhost
      port: 9200
#      username: elastic
#      password: 123456
#      index: indexName
#      crtName: http_ca.crt

server:
  port: 8083
