spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtest?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 10
      max-active: 10

  redis: # 缓存
    host: 127.0.0.1
    port: 6379
    timeout: 6000ms  # 连接超时时长（毫秒）
    database: 0
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接

  elasticsearch:
    rest:
      enable: true
      uris: localhost:9200
      host: localhost
      port: 9200
#      username: elastic
#      password: 123456
#      index: indexName
#      crtName: http_ca.crt

server:
  port: 8083

mybatis-plus:
  mapper-locations: classpath:com.cui.demo.mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
